myTestOutput/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Acceptances__c</fullName>
        <label>Acceptances</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Units_Available__c</fullName>
        <formula>Original_Units_Available__c-Acceptances__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Units Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This is a description of the offer (ie. 
Organic Strawberries)</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Units_Available__c</fullName>
        <label>Original Units Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Valid_Through__c</fullName>
        <label>Valid Through</label>
        <type>Date</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myTestOutput/objects/Offer_Result__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Offer Results</relationshipLabel>
        <relationshipName>Offer_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Results</relationshipLabel>
        <relationshipName>Offer_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Offer Result</label>
    <nameField>
        <displayFormat>OFS-{000000}</displayFormat>
        <label>Offer Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

myTestOutput/classes/ContactExtController.cls
public with sharing class ContactExtController {
    
     public Id cid {get;set;}
     public Id offerid {get;set;}
     public Contact Con {get;set;}
   //  public List<Offer__c> validoffers {get;set;}
    
     public ContactExtController (ApexPages.StandardController controller) {
      
        this.Con = (Contact)controller.getRecord();
        this.cid = controller.getId();
       
        
      }
      
      public List<Offer__c> getvalidoffers() {
          
          List<Offer__c> validoffers = new List<Offer__c>();
          validoffers = [select description__c, Valid_Through__c, Current_Units_Available__c from offer__c where
           Current_Units_Available__c>0];
          
          return validoffers;
        
      }
      
      public pagereference done() {
        pagereference pg = new pagereference('/'+cid);
        pg.setredirect(true);
        
        return pg;
        
      }
      
      public pagereference accept() {
        Offer__c thisoffer = new Offer__c();
        if(offerid == null){
        offerid = Apexpages.currentPage().getParameters().get('sf_id');
        }
        system.debug('offer id ' + offerid);
        thisoffer = [select Acceptances__c, Original_Units_Available__c, Current_Units_Available__c from offer__c where id = :offerid];
        system.debug('Original_Units_Available__c OLD is ' + thisoffer.Original_Units_Available__c);
        system.debug('Acceptances__c OLD is ' + thisoffer.Acceptances__c);
        system.debug('Current_Units_Available__c OLD is ' + thisoffer.Current_Units_Available__c );
     
        if(thisoffer.Current_Units_Available__c<=0) {
        
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Offer is Oversold'));
           return null;
        }
         system.debug('Original_Units_Available__c NEW is ' + thisoffer.Original_Units_Available__c);
        system.debug('Acceptances__c NEW is ' + thisoffer.Acceptances__c);
        system.debug('Current_Units_Available__c NEW is ' + thisoffer.Current_Units_Available__c );
      
        Offer_result__c orc = new Offer_result__c();
        orc.contact__c = this.cid;
        orc.offer__c = offerid;
        insert orc;
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING,'Offer is accepted'));
        return null;
     //   pagereference pg = new pagereference('/apex/ViewOffersMessage?id='+cid);
     //   pg.setredirect(true);
     //   return pg;
      }
      
      
}